---
title: "import R"
author: "黃榆珮"
date: "2019年3月11日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#rm=remove(表單)
#str=strcture
#int=整數
#header:有表投的意思
#colClasses=欄位屬性
```{r}
rm(list=ls())
etf4<-read.table("ETF4_2000_2018_d.txt", fileEncoding = "UTF-8-BOM")
head(etf4)
etf4<-read.table("ETF4_2000_2018_d_ansi.txt", header = T)
str(etf4)
etf4<-read.table("ETF4_2000_2018_d_ansi.txt", header = T, stringsAsFactors = T, 
                 colClasses = c("證券代碼"="character"))
str(etf4)
head(etf4)
etf4<-read.csv("ETF4_2000_2018_d.csv", colClasses = c("證券代碼"="character"))
str(etf4)
etf4.csv<-read.csv("ETF4_2000_2018_d.csv", fileEncoding='big5',
                   colClasses=C('factor','factor','factor','numeric','numeric'))
head(etf4.csv)
str(etf4.csv)
```

```{r}
library(readr)
etf4_csv<-read_csv("ETF4_2000_2018_d.csv")
etf4_csv<-read_csv("ETF4_2000_2018_d.csv", locale = locale(encoding='big5'))
head(etf4_csv)
str(etf4_csv)
library(readxl)
etf4_xls<-read_excel("ETF4_2000_2018_d.xls", 
                     col_types =c("text", "text","text", "numeric","numeric"))
head(etf4_xls)
```
#colnames:name of columns(欄位名稱)
```{r}
etf4.c<-etf4_csv[, c(-2, -4)]
etf4.c<-etf4.c[-1,]
colnames(etf4.c)<-c("id", "date", "price")
library(magrittr)
install.packages("dplyr")
library(dplyr)
etf4.c<-etf4_csv%>%select(c(1,3,5))%>%rename("id" = "證券代碼", "date"= "日期", "price" = "當日均價(元)")
etf4.c
```
#reorder:重新整理
#xts:專門處理時間數列資料
#as.Date:轉換成日期資料
#pipe operator:刪除多餘贅字
```{r}
install.packages("reshape2")
library(reshape2)
etf4.reorder = dcast(etf4.c, date~id)
dim(etf4.reorder)
head(etf4.reorder)
str(etf4.reorder)
etf4.reorder$date<-as.Date(as.character(etf4.reorder$date), "%Y%m%d") 
head(etf4.reorder)
str(etf4.reorder)
install.packages("xts")
library(xts)
etf4.xts<-xts(etf4.reorder[,-1], order.by = etf4.reorder$date)
head(etf4.xts)
tail(etf4.xts)
str(etf4.xts)
```
#na.locf:補滿
```{r}
etf4.xts<-na.locf(etf4.xts)                
tail(etf4.xts)
etf4.xts.fill<-na.locf(etf4.xts, fromLast = TRUE) 
head(etf4.xts.fill)
```

```{r}
etf4.xts<-na.omit(etf4.xts)
head(etf4.xts)
install.packages("tidyr")
library(tidyr)
etf4.xts1<-etf4.xts[complete.cases(etf4.xts),]
head(etf4.xts1)
```
#readRDS:儲存大資料
```{r}
write.csv(etf4.xts, file = "myetf4.csv")
write.zoo(etf4.xts, sep = ',', file = "myetf4.csv.1")
saveRDS(etf4.xts, file = "etf4.xts.rds")
etf4.xts2 <- readRDS("etf4.xts.rds")
head(etf4.xts2)
etf4.zoo <- read.zoo("myetf4.csv.1", header = TRUE, index.column =1, 
                     sep = ",", format = "%Y-%m-%d")
head(etf4.zoo)
class(etf4.zoo)
etf4.xts3<-as.xts(etf4.zoo)
head(etf4.xts3)
```

```{r}
etf4_2016<-etf4.xts['2016']
etf4_2016_01_06 <- etf4.xts["20160101/20160630"]
head(etf4_2016_01_06)
lastweek <- last(etf4_2016, "1 week")
last(lastweek, 2)
first(lastweek, "-2 days")
```